### ISSUE TITLE
Up to date images?

### ISSUE THREAD

**Issue by chrisdonahue** [mkandes/naked-singularity#1]
Thank you for this excellent resource. Is there a location on SDSC where I can run the latest images? The images in `/oasis/scratch/comet/mkandes/temp_project/singularity/images/` do not appear to be up to date; for example `tensorflow-gpu.img` appears to only have CUDA 8, while `tensorflow-gpu.def` (in this repository) appears to install CUDA 9.2

Cheers,
Chris

**Comment by mkandes** [comment]
Hi @chrisdonahue, 

Thanks! And yes, you can find the latest versions on Comet. We migrated the builds to these two locations [1] [2] for CPU-only and GPU-accelerated versions, respectively. You'll also notice we're trying to do a better job of maintaining an archive of previous versions of each container. e.g. [3]. 

Let me know if you have any additional questions.

Thanks,

Marty

[1]

/share/apps/compute/singularity/images/

[2]

/share/apps/gpu/singularity/images/

[3]

[mkandes@comet-ln3 images]$ ls -lahtr /share/apps/gpu/singularity/images/tensorflow/
total 22G
-rwxr-xr-x 1 mkandes sdsc 7.1G Jul  5 08:56 tensorflow-v1.8-gpu-20180627.simg
-rwxr-xr-x 1 mkandes sdsc 7.5G Oct 10 10:38 tensorflow-v1.11-gpu-20181008.simg
-rwxr-xr-x 1 mkandes sdsc 7.5G Nov  5 10:06 tensorflow-v1.11-gpu-20181031.simg
lrwxrwxrwx 1 mkandes sdsc   34 Nov  6 11:31 tensorflow-gpu.simg -> tensorflow-v1.11-gpu-20181031.simg
drwxr-xr-x 2 mkandes sdsc 4.0K Nov  6 11:31 .
drwxr-xr-x 9 mkandes sdsc 4.0K Dec  3 14:22 ..
[mkandes@comet-ln3 images]$

**Comment by chrisdonahue** [comment]
Thanks for the pointer! Extremely helpful
