### ISSUE TITLE
Building Singularity containers via Github Actions

### ISSUE THREAD

**Issue by zonca** [mkandes/naked-singularity#10]
I was wondering if you could automatically build the containers directly on Github actions,
so I made a little test with the Ubuntu 20.04 image and it seems to be working fine:

See the workflow, from https://github.com/singularityhub/github-ci:

https://github.com/zonca/singularity_github_ci/blob/main/.github/workflows/native-install.yml

Log of a build:

https://github.com/zonca/singularity_github_ci/runs/6718361783?check_suite_focus=true

Package:

https://github.com/zonca/singularity_github_ci/runs/6718361783?check_suite_focus=true

I tested it on Expanse with:

    singularity pull oras://ghcr.io/zonca/singularity_github_ci:ubuntu-20.04

**Comment by mkandes** [comment]
Hi Andrea,

Thanks for giving this a try. I've been planning on setting up a build service to help turn around these containers quicker (and replace the SinglarityHub build service I used in the past). Unfortunately, I don't think the free GitHub VMs here will be able to build most of the larger end-user containers we maintain. But that's always sort of been the problem with the 'free' build services available.

Marty
________________________________
From: Andrea Zonca ***@***.***>
Sent: Thursday, June 2, 2022 6:09 PM
To: mkandes/naked-singularity ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [mkandes/naked-singularity] Building Singularity containers via Github Actions (Issue #10)


I was wondering if you could automatically build the containers directly on Github actions,
so I made a little test with the Ubuntu 20.04 image and it seems to be working fine:

See the workflow, from https://github.com/singularityhub/github-ci<https://urldefense.com/v3/__https://github.com/singularityhub/github-ci__;!!Mih3wA!Gxb6rcQt3yaI58AQkqb6WNDhpVeT2z8G2IUXMq8UM9Crj6B9xDtYOBPggigO4u9OSXWaj_OnpFOhu9_J74yl3TQ$>:

https://github.com/zonca/singularity_github_ci/blob/main/.github/workflows/native-install.yml<https://urldefense.com/v3/__https://github.com/zonca/singularity_github_ci/blob/main/.github/workflows/native-install.yml__;!!Mih3wA!Gxb6rcQt3yaI58AQkqb6WNDhpVeT2z8G2IUXMq8UM9Crj6B9xDtYOBPggigO4u9OSXWaj_OnpFOhu9_JoX2JQpc$>

Log of a build:

https://github.com/zonca/singularity_github_ci/runs/6718361783?check_suite_focus=true<https://urldefense.com/v3/__https://github.com/zonca/singularity_github_ci/runs/6718361783?check_suite_focus=true__;!!Mih3wA!Gxb6rcQt3yaI58AQkqb6WNDhpVeT2z8G2IUXMq8UM9Crj6B9xDtYOBPggigO4u9OSXWaj_OnpFOhu9_JGMkwycI$>

Package:

https://github.com/zonca/singularity_github_ci/runs/6718361783?check_suite_focus=true<https://urldefense.com/v3/__https://github.com/zonca/singularity_github_ci/runs/6718361783?check_suite_focus=true__;!!Mih3wA!Gxb6rcQt3yaI58AQkqb6WNDhpVeT2z8G2IUXMq8UM9Crj6B9xDtYOBPggigO4u9OSXWaj_OnpFOhu9_JGMkwycI$>

I tested it on Expanse with:

singularity pull oras://ghcr.io/zonca/singularity_github_ci:ubuntu-20.04

**Comment by zonca** [comment]
do you think the 6 hours max job execution time is not enough?
or the hardware?

2-core CPU
7 GB of RAM memory
14 GB of SSD disk space

If you have a specific container in mind, I can give it a try.

**Comment by mkandes** [comment]
Andrea,

Both. For example, I typically build the PyTorch and TensorFlow containers on VMs with 6 cores, 16 GB ram, and 120 GB disk and the builds can last longer than 8 hours when compiling from source. So, self-hosted runners would be needed for containers like these. But the resource constraints here on the storage might not even be enough to build a base CUDA-enabled container --- probably borderline.

Marty
________________________________
