### ISSUE TITLE
Requesting an image with Tensorflow 1.12

### ISSUE THREAD

**Issue by chrisdonahue** [mkandes/naked-singularity#3]
Context: https://github.com/mkandes/naked-singularity/pull/2

Requesting an image which builds Tensorflow 1.12, likely the mast major update of Tensorflow before the 2.0 release. This is already in progress by @mkandes .

**Comment by chrisdonahue** [comment]
Hey @mkandes . Really hate to bother you but is there any way the 1.12 image could be built? Or could you give me your updated def file so I can build it myself? Hoping to run some experiments over the weekend :)

Cheers,
Chris

**Comment by chrisdonahue** [comment]
Thank you so much for your help! I am testing the image now :)

**Comment by chrisdonahue** [comment]
Everything works and I am getting 99% GPU usage on my jobs. You are a lifesaver!!!

**Comment by mkandes** [comment]
@chrisdonahue,

I've updated the 'tensorflow-gpu.simg' container on Comet to TensorFlow v1.12 [1] and pushed the changes to the repository here. Let me know if you run into any problems.

Thanks,

Marty

[1]

```bash
[mkandes@comet-ln2 ~]$ ls -lahtr /share/apps/gpu/singularity/images/tensorflow/
total 30G
-rwxr-xr-x 1 mkandes sdsc 7.1G Jul  5 08:56 tensorflow-v1.8-gpu-20180627.simg
-rwxr-xr-x 1 mkandes sdsc 7.5G Oct 10 10:38 tensorflow-v1.11-gpu-20181008.simg
-rwxr-xr-x 1 mkandes sdsc 7.5G Nov  5 10:06 tensorflow-v1.11-gpu-20181031.simg
drwxr-xr-x 9 mkandes sdsc 4.0K Dec  3 14:22 ..
-rwxr-xr-x 1 mkandes sdsc 7.6G Dec 20 13:24 tensorflow-v1.12-gpu-20181218.simg
lrwxrwxrwx 1 mkandes sdsc   34 Dec 21 11:01 tensorflow-gpu.simg -> tensorflow-v1.12-gpu-20181218.simg
drwxr-xr-x 2 mkandes sdsc 4.0K Dec 21 11:01 .
[mkandes@comet-ln2 ~]$
```

**Comment by chrisdonahue** [comment]
I **really** appreciate your help with this. If there's anything I can do to thank you (e.g. giving glowing feedback to a supervisor) let me know.
