### ISSUE TITLE
git command not found. updatedb command not found

### ISSUE THREAD

**Issue by Usman095** [mkandes/naked-singularity#4]
I was building the container using the definition file comet/pytorch/pytorch-gpu.def and ran into this issue where it said git command not found. 
I looked at the definition file and git wasn't being installed before the command was used.
The other issue is that mlocate is not being installed before you call the updated command near the end of the definition file.

**Comment by mkandes** [comment]
@Usman095: Thanks for your note here. I'm a bit confused. I did a rebuild of the container myself from the definition file and do not observe the issues you're reporting here. Can I ask what type of operating system does the machine you're using to build the container run? I might have one idea what the issue could be. 

Marty
