### ISSUE TITLE
need to access keras-tensorflow-gpu

### ISSUE THREAD

**Issue by rmojgani** [mkandes/naked-singularity#5]
Hi, 

I used to use "keras-tensorflow-gpu" loaded on comet 
" /share/apps/gpu/singularity/images/keras/keras-tensorflow-gpu.simg" 

With comet being decommissioned, I was hoping I can get it on Expanse, however, cannot find how to build/pull it.

Any help would be appreciated

**Comment by mkandes** [comment]
Hi @rmojgani,

I've placed a copy of this container image on Expanse here [1]. However, please note that this version of TensorFlow is now quite old and Keras is no longer a standalone framework as it was when this container was built. I'd definitely recommend you look into updating your TensorFlow/Keras models to TensorFlow v2 and its new builtin Keras API [2] in the not-too-distant future as it may become difficult to maintain support for this container at some point.

Marty

[1]

/cm/shared/apps/containers/singularity/tensorflow/keras-v2.2.4-tensorflow-v1.12-gpu-20190214.simg

[2]

https://www.tensorflow.org/api_docs/python/tf/keras
